### Create User
POST http://localhost:3000/users
Content-Type: application/json

{
  "fullName": "Ahmad Saifudin",
  "userName": "ahmad123",
  "password": "securepass",
  "email": "ahmad123@example.com"
}

### Login User
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "ahmad123@example.com",
  "password": "securepass"
}
